name: ProSolAdv
channels:
  - defaults
dependencies:
  - setuptools==58.0.4
  - wheel==0.37.1
  - _libgcc_mutex==0.1
  - sqlite==3.38.0
  - python==3.8.13
  - tk==8.6.11
  - ca-certificates==2022.3.18
  - openssl==1.1.1n
  - xz==5.2.5
  - zlib==1.2.11
  - pip==21.2.4
  - certifi==2021.10.8
  - pip:
    - gradio==2.8.14
    - pandas==1.4.1
    - torch==1.10.0
    - transformers==4.17.0
    - jinja2==3.1.1

