name: ProSolAdv
channels:
  - defaults
dependencies:
  - _openmp_mutex==4.5=1_gnu
  - ncurses==6.3
  - setuptools==58.0.4
  - wheel==0.37.1
  - _libgcc_mutex==0.1
  - sqlite==3.38.0
  - python==3.8.13
  - tk==8.6.11
  - libgomp==9.3.0
  - ca-certificates==2022.3.18
  - readline==8.1.2
  - openssl==1.1.1n
  - xz==5.2.5
  - zlib==1.2.11
  - ld_impl_linux-64==2.35.1
  - libgcc-ng==9.3.0
  - pip==21.2.4
  - libstdcxx-ng==9.3.0
  - certifi==2021.10.8
  - libffi==3.3
  - pip:
    - gradio==2.8.14
    - pandas==1.4.1
    - torch==1.10.0
    - transformers==4.17.0
    - jinja2==3.1.1

